version: '3.2'
    
services:
  trx-api:
    command: npm run start
    ports:
      - ${HYPHA_BTC_TREASURY_API_PORT}:3000
    environment:
      - BWS_CREDENTIALS_DIR=/bws-credentials
      - BWS_URL
      - BWS_LOG_LEVEL
      - BWS_TIMEOUT
      - DFUSE_EOS_API_KEY
      - DFUSE_EOS_NETWORK
      - DFUSE_ETH_API_KEY
      - DFUSE_ETH_NETWORK
      - DFUSE_TELOS_API_KEY
      - DFUSE_TELOS_NETWORK
      - WEB3_ENDPOINT
    restart: on-failure